### ISSUE TITLE
"error: relocation overflow: reference to local symbol" during linking

### ISSUE THREAD

**Issue by mdavis777** [rakuco/meta-crosswalk#3]
Error message comes up during linking step:
Yocto: Pyro 2.3
Host OS x86_64 (Centos 7)
Target Machine: genericx86_64 / intel-corei7-64.
Tried gold and bfd linker.  
All Chromium 60 versions have the issue, Chromium 59 compiles fine.

**Comment by rakuco** [comment]
What `MACHINE` value are you using exactly? Can you post the error message along with the command line that was used to link the `chrome` binary?

**Comment by mdavis777** [comment]
Machine is a custom one, but it is based on corei7-64 from meta-intel.
I will post the error as soon as I regenerate it.  Downgrading to Chrome-59 wiped the directory.

I will also do a build with a standard machine and make sure it isn't my custom machine messing something up.

Don't know if it is related, but another difference is I am using nodejs 6 from meta-nodejs.

**Comment by mdavis777** [comment]
Attaching error log for custom machine.  Default standard machine is still building.

[customMachineerror.txt](https://github.com/rakuco/meta-crosswalk/files/1234786/customMachineerror.txt)

Standard i586 machine worked fine.  Trying genericx86_64 and base corei7-64 from meta-intel to see if it is just my machine messing things up.

Standard genericx86_64 and corei7-64 machines both had the same error.  It seems to be related directly to 64bit builds.

Other two error messages
https://gist.github.com/mdavis777/d45de47aae95243eb823ce9284cdfe00

**Comment by rakuco** [comment]
Hmm indeed, I've managed to reproduce the issue myself here with `MACHINE="intel-corei7-64"`.

**Comment by joone** [comment]
I fixed this problem: https://github.com/rakuco/meta-crosswalk/pull/4

**Comment by rakuco** [comment]
I've merged a slightly modified version of @joone and pushed it to my `chromium60` branch.

I'll continue investigating this; I was able to reproduce it with a local desktop build on Fedora 26 (GCC 7 and binutils 2.27) when I pass `-g` to the compiler, but when I use Chromium's own binutils copy (based on binutils 2.26) linking works just fine.
